log:
  level: 0

http:
  port: 8000

admin_password: "admin123456"

pg:
  dsn: "host=localhost user=panda-wiki password=panda-wiki-secret dbname=panda-wiki port=5432 sslmode=disable TimeZone=Asia/Shanghai"

mq:
  type: "nats"
  nats:
    server: "nats://localhost:4222"
    user: "panda-wiki"
    password: ""

rag:
  provider: "ct"
  ct_rag:
    base_url: "http://localhost:8080/api/v1"
    api_key: "sk-1234567890"

redis:
  addr: "localhost:6379"
  password: ""

auth:
  type: "jwt"
  jwt:
    secret: "your-jwt-secret-key-here"

s3:
  endpoint: "localhost:9000"
  access_key: "s3panda-wiki"
  secret_key: "minio-secret-key"
  max_file_size: 20971520

caddy_api: "/app/run/caddy-admin.sock"
subnet_prefix: "127.0.0" 