version: '3.8'

services:
  # Redis 缓存
  redis:
    image: redis:6-alpine
    container_name: panda-wiki-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # NATS 消息队列
  nats:
    image: nats:2-alpine
    container_name: panda-wiki-nats
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"  # NATS port
      - "8222:8222"  # Monitoring port
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO 对象存储 (S3兼容)
  minio:
    image: minio/minio:latest
    container_name: panda-wiki-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: s3panda-wiki
      MINIO_ROOT_PASSWORD: minio-secret-key
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


  # # PandaWiki API服务
  # panda-wiki-api:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.api
  #     args:
  #       VERSION: dev
  #   container_name: panda-wiki-api
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - POSTGRES_PASSWORD=panda-wiki-secret
  #     - JWT_SECRET=your-jwt-secret-key-here
  #     - ADMIN_PASSWORD=admin123456
  #     - S3_SECRET_KEY=minio-secret-key
  #     - NATS_PASSWORD=
  #     - REDIS_PASSWORD=
  #   volumes:
  #     - ./backend/config/config.dev.yml:/app/config.yml
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     nats:
  #       condition: service_healthy
  #     minio:
  #       condition: service_healthy
  #   networks:
  #     - default

  # # PandaWiki Consumer服务
  # panda-wiki-consumer:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.consumer
  #   container_name: panda-wiki-consumer
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_PASSWORD=panda-wiki-secret
  #     - JWT_SECRET=your-jwt-secret-key-here
  #     - ADMIN_PASSWORD=admin123456
  #     - S3_SECRET_KEY=minio-secret-key
  #     - NATS_PASSWORD=
  #     - REDIS_PASSWORD=
  #   volumes:
  #     - ./backend/config/config.dev.yml:/app/config.yml
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     nats:
  #       condition: service_healthy
  #     minio:
  #       condition: service_healthy
  #     panda-wiki-api:
  #       condition: service_started
  #   networks:
  #     - default

volumes:
  redis_data:
  minio_data:
  # portainer_data:

networks:
  default:
    name: panda-wiki-network 